### ISSUE TITLE
Generate custom examples for overview.html

### ISSUE THREAD

**Issue by dpoeschl** [KirillOsenkov/SourceBrowser#11]
Currently the examples on [overview.html](https://github.com/KirillOsenkov/SourceBrowser/blob/master/src/SourceIndexServer/overview.html) are hard-coded .NET reference source examples (`BitConverter`, `Enumerable.cs`, etc.), and so the example links don't work as expected. Can this be changed to use examples from the analyzed project instead?

**Comment by KirillOsenkov** [comment]
First off, there's a way to transform overview.html as part of website generation - see StampOverviewHtmlText():
http://sourcebrowser.azurewebsites.net/#HtmlGenerator/Pass2-Finalization/SolutionFinalizer.cs,201cc918a7db413e

You could extend it to write arbitrary content into resulting overview.html.

Second, as part of index generation you can collect one example for each usage. I imagine a data type FeatureExample or similar where it has text for the feature name (in the left column) and example URL (in the right column). SolutionGenerator should have a List<FeatureExample> where you fill it up as you go.

When writing overview.html foreach over those examples and generate HTML into a table. This is actually nice because that page is missing quite a lot of features I added recently.

You can place the actual code that returns you a chunk of HTML from FeatureExample into the Markup class.

**Comment by KirillOsenkov** [comment]
Unfortunately I'll probably never get to it.
