### ISSUE TITLE
MSBuild Tools required for Microsoft.Build.Runtime

### ISSUE THREAD

**Issue by SuperRajar** [KirillOsenkov/SourceBrowser#130]
I have an application using the Microsoft.Build nuget packages to compile some C# code. With MSBuild 2015 installed on the machine everything works fine. However I want to get rid of the MS Build Tools prerequisite and as I understand it Microsoft.Build.Runtime is supposed to solve that issue. In the description is says "This package delivers a complete executable copy of MSBuild. Reference this package only if your application needs to load projects or execute in-process builds without requiring installation of MSBuild.".

But if I run the code on machine without MSBuild Tools installed I get the same error message (Could not load file or assembly 'System.Threading.Tasks.Dataflow) even though I have included the Microsoft.Build.Runtime package. Have I misunderstood something or do I just need to Initialize the the Build.Runtime somehow?

**Comment by KirillOsenkov** [comment]
Hi, I'm not sure since I've never used those packages, but as a rule you need proper MSBuild installed on the machine for SourceBrowser to work properly. Other scenarios are unsupported and you're on your own there. Good luck! 

May I also recommend http://msbuildlog.com for investigating MSBuild issues, it's a nice tool.
