### ISSUE TITLE
add user/pass

### ISSUE THREAD

**Issue by luisrudge** [KirillOsenkov/SourceBrowser#2]
so we can all stop worrying about our source code open in the web :D

**Comment by KirillOsenkov** [comment]
I'll leave this as an exercise to the reader ;) I expect people who use this to have some level of customization for their goals, and this looks like one such example.

**Comment by luisrudge** [comment]
why not adding an option to the command line runner?

**Comment by KirillOsenkov** [comment]
I explicitly don't want to be in the business of protecting the generated website with authentication and authorization because I will never come up with a solution that is good enough for everybody. I don't want to be in the business of protecting the source code of companies that do not want it public. It should be explicit that it is their responsibility and I am not providing any help or common mechanisms to support that. Otherwise if there is a vulnerability I can be blamed for someone stealing someone else's code. Web security is serious business and should be left to the experts. I am not competent to write this code and I won't accept any contributions that think they are ;)

So unfortunately I'm going to have to close this one. Good suggestion, but it is best left to the consumers. I just provide the engine.
