### ISSUE TITLE
Tolerate %2c (encoded comma) in URLs

### ISSUE THREAD

**Issue by jnm2** [KirillOsenkov/SourceBrowser#212]
> Another thing I noted is that some sites, like Azure Devops, encodes the comma (which [seems to be correct behavior](https://stackoverflow.com/questions/8828702/why-is-the-comma-url-encoded)). The URL for source.dot.net does not work when the comma is URL encoded: https://source.dot.net/#System.Private.CoreLib/CancellationTokenSource.cs%2c1008 (notice the `%2c`; If you replace it for a comma, then it works).

_Originally posted by @andre-ss6 in https://github.com/KirillOsenkov/SourceBrowser/issues/95#issuecomment-702392532_

**Comment by KirillOsenkov** [comment]
I attempted a fix in https://github.com/KirillOsenkov/SourceBrowser/commit/9c24e9ca76351524c9f973ab4fdd12d7a0069bbf, but it's a tricky area.

In hindsight, of course I regret using this custom Url scheme, especially because a comma is a valid part of a file name, and we did encounter files having commas over the years.

Please review the fix and let me know if it looks OK. Ideally if you could try it out to see if it works as you expect.
