### ISSUE TITLE
SourceBrowser Error

### ISSUE THREAD

**Issue by modulexcite** [KirillOsenkov/SourceBrowser#28]
Hi,

HTMLGenerator seems to writing the below error message on every solution I run it against. It continues with building the site and successfully completes it but I'm not sure what the below error is meant to be. Any help on this would be appreciated.
PS: The tool is just awesome and thanks for sharing it with the public.

First chance exception
System.EntryPointNotFoundException: Unable to find an entry point named 'ReadFile' in DLL 'api-ms-win-core-file-l1-2-0.dll'.
   at System.Reflection.Internal.FileStreamReadLightUp.NativeMethods.ReadFileModern(SafeHandle fileHandle, Byte* buffer, Int32 byteCount, Int32& bytesRead, IntPtr overlapped)
   at System.Reflection.Internal.FileStreamReadLightUp.TryReadFile(Stream stream, Byte* buffer, Int64 start, Int32 size)

**Comment by modulexcite** [comment]
I forgot to mention that I'm on a Windows 7 64bit OS with VS 2015, not sure if that matters.

**Comment by KirillOsenkov** [comment]
Hm, believe it or not, I've seen similar ones a few times and never was able to determine what's going on. They're completely benign, you can just ignore them. If they get too annoying, you can filter them out by adding into approved exception whitelist like I did here:
http://sourcebrowser.azurewebsites.net/#HtmlGenerator/Utilities/FirstChanceExceptionHandler.cs

Glad you like the tool. Enjoy.

**Comment by modulexcite** [comment]
great thanks for your help.

**Comment by sixlettervariables** [comment]
As a follow-up, is the following a similarly "ignorable" first chance exception?

```
16:51:55 5/16/2016 4:51:55 PM: First chance exception
System.InvalidCastException: Unable to cast object of type 'Microsoft.Bcl.Build.
Tasks.ValidatePackageReferences' to type 'Microsoft.Build.Framework.ITask'.
   at Microsoft.Build.Shared.TaskLoader.CreateTask(LoadedType loadedType, String
 taskName, String taskLocation, Int32 taskLine, Int32 taskColumn, LogError logEr
ror, AppDomainSetup appDomainSetup, Boolean isOutOfProc, AppDomain& taskAppDomai
n)
```

**Comment by KirillOsenkov** [comment]
Yup. This results from different versions of Microsoft.Build.Tasks.Core.dll and/or Microsoft.Build.Tasks.v4.0.dll or Microsoft.Build.Tasks.v12.0.dll loaded in the same process.

If when you see this in the debugger you open Debug -> Windows -> Modules, you will see multiple versions of the tasks dll loaded side-by-side. The cast fails because the type ITask is defined in one version of the dll and ValidatePackageReferences is defined in the other one.

I haven't investigated this in details, as it's highly likely benign, but I think one could fix this by adding an assembly binding redirect into HtmlGenerator.exe.config (app.config of the HtmlGenerator project) that redirects one version of the tasks dll to the newer one.

I think if you look at C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe.config it will show you an example of such redirects. HtmlGenerator should have similar ones to mimic the exact MSBuild behavior.

If you do investigate and manage to fix this, please report back. Maybe we should fix it for everyone.
