### ISSUE TITLE
HtmlGenerator sometimes misses references

### ISSUE THREAD

**Issue by drose-d2l** [KirillOsenkov/SourceBrowser#41]
I have noticed that when using a number of assemblies, that the HtmlGenerator sometimes misses references / symbols.

As an example:
https://referencesource.microsoft.com/#System.Security/system/security/cryptography/xml/cipherdata.cs,79
The XmlDocument class has not been given a symbol and cannot be linked or referenced.

Edit: for the above, the entire assembly does not recognize symbols within System.Xml

**Comment by KirillOsenkov** [comment]
This is usually the result of the project being indexed not building correctly or some errors in the project or the referenced projects. The process by which referencesource.microsoft.com is generated is unfortunately really prone to errors due to the way the .NET source code is built internally.

But if you're seeing problems like these in your own website/codebase, it's possible to investigate and fix. You can start by uncommenting this line:
http://sourcebrowser.azurewebsites.net/#HtmlGenerator/Pass1-Generation/DocumentGenerator.References.cs,161
and debugging through it. It will show what the build error was and this may give you hints on how to investigate it further.

**Comment by drose-d2l** [comment]
Sorry I have not been active on this issue. This does not seem to be an issue, it looks like the way our projects are set up the assemblies are required to actually obtain all the proper references. 

I am going to close this as it was an issue on my end!
