### ISSUE TITLE
Have a way to turn the Git blame feature on or off and make it off by default

### ISSUE THREAD

**Issue by KirillOsenkov** [KirillOsenkov/SourceBrowser#57]
We shouldn't assume that the majority of the solutions are in Git and even if so, that users want to pay for this feature by default. 

I think it should be opt-in. We should also advertise this so that it's obvious to users that this feature exists and have a Wiki page on how to turn it on and how to use it.

**Comment by KirillOsenkov** [comment]
Hey @ddurschlag would you be interested in helping with this?

**Comment by ddurschlag** [comment]
Hi @KirillOsenkov ,

Sure! The git blame feature is a plug-in, so if you delete it from the plugins directory it won't be used -- there's no direct coupling to it in the main code-base. After some consideration, I left it in by default as an example plug-in. I believe, if the solution is not in git, that it does nothing, but I might have screwed that up.

How would you like this to work? Include it as a sample, but not in the plug-ins directory (so it's not in use)? Don't include it, but provide docs? Something else entirely? Any of these solutions should be easy to implement.

**Comment by KirillOsenkov** [comment]
That is a great design and I love it.

How about a command-line switch that says /usegitblame or something? When you scan for extensions, include or exclude your extension based on the flag, and default to false?

Or a config file with a white-list of all extensions to include? (Or blacklist all extensions to exclude?) The .dll name of the MEF assembly should be the name of the extension.

Definitely it'd be great to have a Wiki page on this project that documents it. Also perhaps include in command-line help (/?) Let me know if you can't edit the Wiki.

**Comment by KirillOsenkov** [comment]
P.S. The reason I'm thinking to exclude it by default is additional performance. I know it's pretty fast but for huge codebases people should be able to opt-in (otherwise they'll never know that their huge builds can get much faster). So not against it in principle, just the perf considerations for large codebases. Thanks!

**Comment by ddurschlag** [comment]
Yeah, the blame is super painful on large/old codebases. We don't run it on our main codebase internally for this very reason! A couple notes:

- I was wrong about where the plugin goes. It just goes in the main DLL pile. The MEF config for this is in PluginAggregator.cs line 27. We could consider having an explicit "plugins" directory to make this more apparent -- this might require other changes to the MEF code, however.

- The output path in release mode is NOT set to the main indexer directory, and thus the plugin will not be on in release mode. I can't remember if this was intentional. I'm declaring it a feature.

- I think a blacklist makes more sense than a whitelist. Requiring two steps (put plugin dll in appropriate place, add to whitelist) to use a plugin feels awkward to me. Perhaps /disableplugins to disable ALL plugins, and /disableplugin:NAME to disable a single one?

I'll try to get to this sometime soon, but if someone else wants to, it should be easy to figure out.

**Comment by KirillOsenkov** [comment]
Thanks!

I like the blacklist and /disableplugin[s]. However keep in mind that discovering .dlls costs a lot (reflection is expensive and you get exceptions for native .dlls), so a whitelist would be better for performance. I do agree that enabling a plugin explicitly is cumbersome, however it just needs to be done once, and I doubt we'll get more plugins anytime soon anyway ;)

**Comment by ddurschlag** [comment]
I actually have another plugin (https://github.com/ddurschlag/BitBucketSourceBrowserPlugin) already. I was additionally planning some others (including ripping out some of the less core built-in functionality, like MSBuildSupport, into plugins that can be disabled and plugins to provide handling for unsupported file types like plain text or non-.Net languages). Also, the plugins load exactly once (at startup time) so the total performance cost is measured in milliseconds. Finally, with a whitelist, it needs to be done every time the indexer is run on the command line (or buried in a config somewhere) neither of which is all that exciting.

Would you prefer the blacklist use dll name or MEF name? The MEF name is likely to be "cleaner" to read and will jibe better with any other logging, but the dll name is easier to discern without going into the source code.

**Comment by ddurschlag** [comment]
Is this now resolved with #60 ?
