### ISSUE TITLE
HtmlGenerator can't deal with multiple csproj's with same assembly name

### ISSUE THREAD

**Issue by FransBouma** [KirillOsenkov/SourceBrowser#7]
I have the following scenario:
One solution, with two projects, P1 and P1.Extended. Both use the namespace 'P1' and the assembly name 'P1'. P1.Extended contains all of P1's code (through file links in the csproj file), and extra classes. I use this in my work to have a .NET 4.5+ build of our runtime with extra classes for async/await support. This way I get multiple dlls with the same name (but stored in different folders), and it's a drop-in replacement to add async. If the assembly name would change, it would be more work for our users as they then had to change the references in their own code to the new file. (the same scenario is also used by e.g. Entity Framework, where they have two builds with the same assembly name, one with and one without async, as one is for .NET 4.0 and the other for .NET 4.5+)

If P1.Extended is the first project in the .sln file, it gets processed by HtmlGenerator and P1 is skipped (not mentioned at all in the output), if P1 is the first file in the sln, P1.Extended is skipped and not mentioned in the output at all. 

I reproduced this with 2 projects with the names above in a simple sln file and both with their own class (class1 and class2) and I added class1 as a file link to P1.Extended. Based on the order in the sln file one is skipped over the other. 

I think it's related to the fact that you can have assembly browsing so the name of the assembly is key here, but that would also skip a set of classes (namely the ones in the Extended assembly if it's lower in the sln file order). Not sure if this is fixable. the workaround is to have the extended project (which should contain all the code of the normal project) first in the sln file. 

I had a .zip ready but GitHub doesn't want me to attach .zip files.

**Comment by KirillOsenkov** [comment]
Yes, this is a known limitation and I've just added a paragraph to readme.md to warn users of this. Only the first project survives, all others with the same name are skipped.

I just added a warning when a project is skipped due to assembly name collision, so at least it won't be silent.

I guess you can fork the repo and in your copy add some code that would skip the assembly with less files. Then the project with more files will always be chosen regardless of their order.

I should think of some sort of config/extension point where you can filter projects from being included in the index. The internal version of Source Browser had a huge file called SpecialCases.cs which would filter out hundreds of "victim" projects where for instance we'd include the desktop mscorlib but filter out the Silverlight one and the CoreCLR one.
